### ISSUE TITLE
Can the Diffusion model generate images of different sizes? Most of the ones I have seen are symmetrical, that is, the length and height are equal. I want to generate images with different lengths and heights. Is it possible?

### ISSUE THREAD

**Issue by wang1528186571** [xavihart/Diff-PGD#10]
Can the Diffusion model generate images of different sizes? Most of the ones I have seen are symmetrical, that is, the length and height are equal. I want to generate images with different lengths and heights. Is it possible?

**Comment by xavihart** [comment]
I think the diffusion model used in this repo cannot.

**Comment by xavihart** [comment]
The input of the classifier is always resized to square, so for Diff-PGD you can also resize it to square and then run Diff-PGD
