### ISSUE TITLE
Info about dataset preparation

### ISSUE THREAD

**Issue by JeanPhilippeMonteuuis** [xavihart/Diff-PGD#12]
Hi, 

Great work.

I was wondering if you could add more information in the README.md about the required folder structure of the dataset (e.g., Imagenet).
I would expect something like:
imagenet/
 -val/ *.JPEG

Thank you

**Comment by xavihart** [comment]
the imagenet val set is organized in the original version, with 1000 classes, each class has 50 samples:
- val
   - 0 
      - 0.png
      - 1.png
      - ...
      - 49.png
 - 1
      - ...
