### ISSUE TITLE
Could you provide the checkpoint to generate face images?

### ISSUE THREAD

**Issue by yuuma002** [xavihart/Diff-PGD#2]
Thank you for open-sourcing your wonderful work. We would like to generate face adversarial examples using Diff-PGD. However, we can only find the checkpoint to generate ImageNet-like images. Could you provide the checkpoint to generate face images, or tell us how to train the model on the face dataset?

**Comment by xavihart** [comment]
i think there are already checkpoints for generating face adversarial images: e.g. https://github.com/NVlabs/edm (FFHQ dataset) and also for Celeba: https://paperswithcode.com/sota/image-generation-on-celeba-64x64
