### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by Raineasy** [xavihart/Diff-PGD#5]
Very glad you shared your code! I'm sorry to bother you, but is the code incomplete, after I installed the corresponding environment as well as the data path, there is still a part of the unknown error, such as in the `denoise.py` file ` from improved_diffusion.script_util import ...` this `improved_diffusion` part and also the `create_argparser()`  in the same file, and `InputCenterLayer()` in the `dataset.py` doesn't seem to appear in the whole code. I run the code on my win10 system. I'm still a novice when it comes to coding, so if you know how to fix my problem I'd appreciate it! :)

**Comment by xavihart** [comment]
Yes, we did not include experiments on CIFAR-10 so the code may not work very well. You can try the diffusion model on ImageNet using our code, which is based on guided diffusion instead of improved diffusion.

**Comment by Raineasy** [comment]
Thank you for your reply！：）
