### ISSUE TITLE
Question about v2 version in attack_global.py

### ISSUE THREAD

**Issue by fengyao12** [xavihart/Diff-PGD#6]
Great job. I have a question, the v2 version doesn't compute the gradient for the diffusion process, although it can be accelerated, is this still equivalent to the v1 version?

**Comment by xichenpan** [comment]
In Sexction 6 of the updated paper , the authors show that v2 can still fool the classifier well (https://openreview.net/pdf?id=JTwxylP6U9)

**Comment by xavihart** [comment]
it is not equivalent, it approximates the jacobian of input over U-Net, making it much faster
