### ISSUE TITLE
How to generate an accurate mask corresponding to the image

### ISSUE THREAD

**Issue by Raineasy** [xavihart/Diff-PGD#7]
Nice and interesting code! But how you generate an accurate mask corresponding to the image. Did you use code processing or some other tool like Photoshop? I don't see the part that generates the mask in your code, they seem to be part of the preprocessed ImageNet dataset. Sorry to bother you again.  👍

**Comment by xichenpan** [comment]
You can use grouned-SAM to generate good masks (https://github.com/IDEA-Research/Grounded-Segment-Anything).
