### ISSUE TITLE
Inquiry About the Input Normalization Operation for Diff-PGD in Custom Models

### ISSUE THREAD

**Issue by GradOpt** [xavihart/Diff-PGD#8]
Thank you for the great work you've done.

While assessing the effectiveness of Diff-PGD adversarial samples, I noticed that the ‘NormalizeLayer’ class in ‘dataset.py’ introduces an input normalization layer for all classifiers. The accompanying description states: "In order to certify radii in original coordinates rather than standardized coordinates, we add the Gaussian noise before standardizing, which is why we have standardization be the first layer of the classifier rather than as a part of preprocessing as is typical."

Currently, I am preparing to use Diff-PGD to test the robustness of a model that I have trained on ImageNet. However, I did not employ input normalization during the training of my model. I'm concerned that introducing it only during testing could introduce bias and might not fairly reflect the model's robustness.

Would omitting input normalization in the Diff-PGD data preparation adversely affect the results? Is it necessary to retrain my classifier with the input normalization step included for a fair and accurate evaluation?

Thank you for any guidance you can provide.

**Comment by xavihart** [comment]
I think it is not a big issue, you can skip the normalization if the data used in your customized model is not normalized during training. The description is unrelated and was used for other projects, please omit that.

**Comment by GradOpt** [comment]
> I think it is not a big issue, you can skip the normalization if the data used in your customized model is not normalized during training. The description is unrelated and was used for other projects, please omit that.

Thank you for your quick response and the excellent work you do. Best regards!
