### ISSUE TITLE
Every time I run the program, the video memory overflows. Where can I adjust the batch?

### ISSUE THREAD

**Issue by wang1528186571** [xavihart/Diff-PGD#9]
Every time I run the program, the video memory overflows. Where can I adjust the batch?

**Comment by xavihart** [comment]
you mean GPU memory overflow? you can try:
(1) use smaller ddim steps, e.g. ddim30
(2) use version='v2'

**Comment by wang1528186571** [comment]
> you mean GPU memory overflow? you can try: (1) use smaller ddim steps, e.g. ddim30 (2) use version='v2'
4080Super ddim10 not can run.This is normal or non-normal?

**Comment by xavihart** [comment]
that may happen if it is 16G
i think v2 may work
